/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-surface": "#131b2e",
        "on-surface-variant": "#5a4138",
        "tertiary-container": "#00873a",
        "surface-variant": "#dae2fd",
        "background": "#faf8ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbce",
        "secondary-fixed-dim": "#bcc7de",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#7f2b00",
        "on-tertiary-fixed-variant": "#005320",
        "tertiary": "#006b2c",
        "inverse-primary": "#ffb598",
        "outline": "#8e7166",
        "on-background": "#131b2e",
        "secondary-container": "#d5e0f8",
        "on-tertiary-fixed": "#002109",
        "surface": "#faf8ff",
        "tertiary-fixed": "#7ffc97",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#370e00",
        "primary-container": "#cb4a00",
        "surface-container": "#eaedff",
        "on-secondary-fixed": "#111c2d",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#a63b00",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#3c475a",
        "inverse-surface": "#283044",
        "surface-dim": "#d2d9f4",
        "surface-container-highest": "#dae2fd",
        "secondary": "#545f73",
        "on-tertiary-container": "#f7fff2",
        "on-primary-container": "#fffbff",
        "outline-variant": "#e2bfb2",
        "on-secondary-container": "#586377",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#62df7d",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed": "#d8e3fb",
        "primary": "#a23a00",
        "primary-fixed-dim": "#ffb598",
        // transit specific accents
        "transit-orange": "#E8590C",
        "transit-green": "#16A34A",
        "transit-red": "#DC2626",
        "transit-amber": "#D97706",
        "transit-slate": "#0F172A",
        "transit-card": "#FFFFFF",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        heading: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "title-lg": ["Inter"],
        "label-code": ["JetBrains Mono"],
        "display-lg": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-lg": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "title-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
      },
    },
  },
  plugins: [],
}
